name: Build LaTeX document
on:
  push:
    branches:
      - 'master'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository contents
      uses: actions/checkout@v1

    - name: Latex compiler
      uses: Jatus93/Latex-multicompiler@master
      with:
        path_to_list: 
          ['Case Discussion/Main.tex', '']
          ['Group Agreement/Main.tex', '']
          ['Group Agreement - For report/Main.tex', '']
          ['Group Agreement - Updated version/Main.tex', '']
